"""add_supplier_extended_fields

Revision ID: a2031a0aba08
Revises: 0d51a17fb904
Create Date: 2026-02-17 15:30:28.950397

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2031a0aba08'
down_revision: Union[str, None] = '0d51a17fb904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('contact_person', sa.String(length=255), nullable=True))
    op.add_column('suppliers', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('suppliers', sa.Column('payment_terms', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('lead_time_days', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('preferred_currency', sa.String(length=10), nullable=True))
    op.add_column('suppliers', sa.Column('tax_id', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('suppliers', sa.Column('categories', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'categories')
    op.drop_column('suppliers', 'notes')
    op.drop_column('suppliers', 'tax_id')
    op.drop_column('suppliers', 'preferred_currency')
    op.drop_column('suppliers', 'lead_time_days')
    op.drop_column('suppliers', 'payment_terms')
    op.drop_column('suppliers', 'website')
    op.drop_column('suppliers', 'contact_person')
    # ### end Alembic commands ###
